### ISSUE TITLE
How to calculate the gradient of metapath embedding?

### ISSUE THREAD

**Issue by sh0416** [csiesheep/hin2vec#15]
If we use binary step function, the gradient of step function is always zero.

I think there is no backpropagation for the metapath embedding vector.

However, there is a update in metapath vector and I don't understand the flag "is_deepwalk".

What is that?

**Comment by sh0416** [comment]
To my knowledge, this implementation update the gradient of sigmoid function to metapath vector whatever we take regularization function we take.

Is it intended?

**Comment by csiesheep** [comment]
Hi, Thanks for asking. Yes, I use the gradient of sigmoid function to approximate the gradient of step function.
