### ISSUE TITLE
Index out of range

### ISSUE THREAD

**Issue by e-yi** [csiesheep/hin2vec#18]
if for a node all edges' weight is smaller than 0.1, than this node is in `HIN.graph` but `HIN.node_choices[node]` is `[]`, which would cause `IndexError`

**Comment by csiesheep** [comment]
Hi, Thanks for asking. Could you give me a sample edge_list file that has this problem? Thanks!

**Comment by e-yi** [comment]
well, I made a mistake... currently this version of code does not support loading a weighted graph, and I've modified it...

Anyway, in case someone needs to dealing with weighted graphs, the problem is caused by this line:
https://github.com/csiesheep/hin2vec/blob/971585fbb01d5cfe9a62dbeb5bdcce4a47a021e8/ds/network.py#L282

if `w<0.1` than it becomes `node_choices[from_id] += []`
