### ISSUE TITLE
Error in main_py.py

### ISSUE THREAD

**Issue by baytasin** [csiesheep/hin2vec#3]
Hi, 
I got the following error when I ran "python main_py.py res/karate_club_edges.txt node_vectors.txt metapath_vectors.txt -l 1000 -d 2 -w 2"

Load a HIN...
U 34
{'U-U': 0}
0 16
1 3
2 1
3 2
4 5
5 2
6 3
7 2
8 9
9 6
10 10
11 6
12 3
13 4
14 4
15 4
16 5
17 4
18 2
19 4
20 3
21 12
22 2
23 17
24 2
25 2
26 2
27 2
28 2
29 5
30 3
31 4
32 3
33 2
Generate random walks...
/tmp/tmp7_cLNl
Reading nodes 340000
Reading paths 670000
0 0(count:339660, inverse:False)
1 0,0(count:339320, inverse:False)
training bytes: 1592525
distinct node count: 34
distinct path count: 2
start training
0.000735 330000/340000 (97.06%) 
Finished. Total time: 1.18 minutes
Dump vectors...
Traceback (most recent call last):
  File "main_py.py", line 160, in <module>
    sys.exit(main(args[0], args[1], args[2], options))
  File "main_py.py", line 67, in main
    output_path2vec(g, tmp_path_vec_fname, path_vec_fname)
  File "main_py.py", line 99, in output_path2vec
    edge = ','.join([id2edge_class[int(id_)] for id_ in ids])
ValueError: invalid literal for int() with base 10: ','

Thank you.

**Comment by jadbin** [comment]
You can temporarily use "python main.py" (not main_py.py) after building the C source in model_c:
create a directory named 'bin' in model_c, then run 'make' command in model_c/src.

P.S. You may get a segment fault error if you use macOS like what I show in the other issue. Ubuntu may be a better choice, at least I haven't see any fatal error while running the program.

**Comment by csiesheep** [comment]
Hi, baytasin

Yes, please use main.py rather than main_py.py. Sorry for the confusing.

Hi, jadbin

Thanks for the help!

**Comment by chenhui-bupt** [comment]
when i modified the code in main_py.py, i solved the problem. see #12
